### ISSUE TITLE
bundle configuration

### ISSUE THREAD

**Issue by mkoubik** [mkoubik/LatteBundle#9]
Allow configuration in config.yml.

```
latte:
    xhtml: false
    macros:
        - My\Macro::install
```
